theme: jekyll-theme-slate
title: Australian Academy of Science Conference on Multiscale Dynamics of the Southern Ocean
description: Part of the Elizabeth and Frederick White Research Conference series
